version: "3.7"
networks:
    twitter:
        external: false

services:
    mysql:
        image: mysql:8
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todos
        ports:
            - "3306:3306"
        networks:
            twitter:
    php:
        build:
            context: ../
            dockerfile: ./docker/apache2/Dockerfile
        depends_on:
            - mysql
        volumes:
            - ../source:/var/www/html:rw
        ports:
            - "80:80"
            - "443:443"
        networks:
            twitter:

volumes:
    mysql-data:
